name: Testar, Construir e Publicar Imagem da Aplicação

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Construir e Publicar Aplicação
    runs-on: ubuntu-latest
    env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    steps:
      - name: Analisar o Código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21
      
      - name: Docker-Compose up
        run: |
          cd docker
          docker compose up -d

      - name: Testes Unitários e de Integração
        run: mvn clean install

      - name: Construir o Projeto
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Construir Imagem do Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/credpago-app:today

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publicar Imagem da Aplicação Spring no Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/credpago-app:today